-- MySQL Script generated by MySQL Workbench
-- Mon Jan  1 16:53:26 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema TodoApp
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema TodoApp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `TodoApp` DEFAULT CHARACTER SET utf8 ;
USE `TodoApp` ;

-- -----------------------------------------------------
-- Table `TodoApp`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TodoApp`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(145) NOT NULL,
  `profileImage` VARCHAR(145) NULL,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `idUser_UNIQUE` (`idUser` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Category` (
  `idCategory` INT NOT NULL AUTO_INCREMENT,
  `idUser` INT,
  `title` VARCHAR(45) NOT NULL,
  `colorHEX` VARCHAR(45) NOT NULL,
  `secondaryColorHEX` VARCHAR(45) NOT NULL,
  `icon` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCategory`, `idUser`),
  INDEX `fk_Category_User1_idx` (`idUser` ASC) VISIBLE,
  UNIQUE INDEX `idCategory_UNIQUE` (`idCategory` ASC) VISIBLE,
  CONSTRAINT `fk_Category_User1`
    FOREIGN KEY (`idUser`)
    REFERENCES `User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Task`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Task` (
  `idTask` INT NOT NULL AUTO_INCREMENT,
  `idUser` INT NOT NULL,
  `idCategory` INT NOT NULL,
  `title` VARCHAR(64) NOT NULL,
  `description` VARCHAR(145) NOT NULL,
  `time` VARCHAR(45) NOT NULL,
  `completed` TINYINT NOT NULL,
  PRIMARY KEY (`idTask`, `idUser`, `idCategory`),
  INDEX `fk_Task_User_idx` (`idUser` ASC) VISIBLE,
  UNIQUE INDEX `idTask_UNIQUE` (`idTask` ASC) VISIBLE,
  INDEX `fk_Task_Category1_idx` (`idCategory` ASC) VISIBLE,
  CONSTRAINT `fk_Task_User`
    FOREIGN KEY (`idUser`)
    REFERENCES `User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Task_Category1`
    FOREIGN KEY (`idCategory`)
    REFERENCES `Category` (`idCategory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
